---
ID: "45d4c8eb-fa39-4311-b6e1-b4117a006271"
Parent: "fa73c22a-1fcc-426e-a81d-684f02700a35"
Template: "fa73c22a-1fcc-426e-a81d-684f02700a35"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Link With Text Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {6AD475FA-174F-46A8-BC93-620ED904508E}
    {FA73C22A-1FCC-426E-A81D-684F02700A35}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
