---
ID: "ae1cef92-bf83-46c6-869f-62c65e39b5d6"
Parent: "29772a30-eb05-428b-b21a-8f8405496ef1"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/OneWeb/OneWeb/OneWeb/Presentation/Rendering Variants/OneWeb Link With Text/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T105154Z
