---
ID: "0146086e-f112-4c8e-bf44-f7ff1a6ba899"
Parent: "7501c76d-ca5a-4436-b9d6-1330d295f3fa"
Template: "7501c76d-ca5a-4436-b9d6-1330d295f3fa"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Text With Placeholder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211129T112128Z
