---
ID: "e8c4dc6e-e526-499d-8439-7e7a7995df5b"
Parent: "27843b52-eb62-4fad-9943-3c07d2755207"
Template: "27843b52-eb62-4fad-9943-3c07d2755207"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Search/Datasource/OneWeb AutoSuggest Search Configuration/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211115T221151Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
