---
ID: "b879f0da-83d3-4196-8de8-653a6b1fcfcd"
Parent: "3ff47763-b0a6-4b2f-a3d1-afdbddf46495"
Template: "3ff47763-b0a6-4b2f-a3d1-afdbddf46495"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Card Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {0D4F3A61-243A-42A9-A33C-9F054E02449B}
    {3FF47763-B0A6-4B2F-A3D1-AFDBDDF46495}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
