---
ID: "0363a2d8-2244-41e3-98c9-a63b1cf1ec18"
Parent: "313b1c7e-a567-469b-a009-b682d61aae09"
Template: "313b1c7e-a567-469b-a009-b682d61aae09"
Path: /sitecore/templates/Foundation/OneWeb/Search/_Base Search Configuration/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211115T221151Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
