---
ID: "1c3f19a0-3f62-4006-9313-9d3843b72c70"
Parent: "4229641b-8fbd-46b0-b87c-cdfafdc08a01"
Template: "4229641b-8fbd-46b0-b87c-cdfafdc08a01"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Rendering Parameters/OneWeb Related Listing Rendering Parameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211202T073644Z
