---
ID: "d31dfd9c-b0ff-402b-84d0-8d6bdbd1bc3b"
Parent: "80af7f03-7454-4121-b229-e187c275f446"
Template: "80af7f03-7454-4121-b229-e187c275f446"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Text With Placeholder Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {7501C76D-CA5A-4436-B9D6-1330D295F3FA}
    {80AF7F03-7454-4121-B229-E187C275F446}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
