---
ID: "e1501181-d4cc-4b2b-b72e-d8a9b48ed340"
Parent: "f9f0b4ff-dfbc-434b-a75f-b2d9a8d8c648"
Template: "f9f0b4ff-dfbc-434b-a75f-b2d9a8d8c648"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Login/Datasource/OneWeb User Email Template/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220324T100033Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
