---
ID: "d829414a-1e6d-478e-938e-ad416a97feaa"
Parent: "b9677eac-297a-4479-88de-7c87bc4ced66"
Template: "b9677eac-297a-4479-88de-7c87bc4ced66"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Job Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {39C1B4E5-0E7E-48AF-BD74-F44C09BC2B7C}
    {B9677EAC-297A-4479-88DE-7C87BC4CED66}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
