---
ID: "966b26f5-36e5-4c33-95d4-b31129d64dc6"
Parent: "f63904e2-d57f-4139-a160-6cf7fae4ba3f"
Template: "f63904e2-d57f-4139-a160-6cf7fae4ba3f"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Login/Rendering Parameters/OneWeb User Login Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220323T132507Z
