---
ID: "97c5955d-8bb5-4e0f-92a9-edc08ecb7ddb"
Parent: "377bca24-5f58-4013-a109-3b0c5260ffcd"
Template: "377bca24-5f58-4013-a109-3b0c5260ffcd"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Structure/OneWeb Section/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211129T112128Z
