---
ID: "3e210a4a-8df3-4099-800e-648eb48bcb2b"
Parent: "1ca6adee-9fe5-4be7-9051-814a32bb89dc"
Template: "1ca6adee-9fe5-4be7-9051-814a32bb89dc"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Locate Distributor/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220218T060812Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
