---
ID: "4225a9be-2f1f-4385-9322-e93bb7cc5d89"
Parent: "acb637d4-de47-4480-b37d-c8e647c9157b"
Template: "acb637d4-de47-4480-b37d-c8e647c9157b"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Structure/Rendering Parameters/OneWeb Column Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211206T170819Z
