---
ID: "2022943d-a60b-4baf-9014-8285e468290a"
Parent: "8f39ab28-6ec9-4476-b3d3-f1ed1ce9eda1"
Template: "54571f1a-cd2e-4215-96f5-f28af4caab48"
Path: /sitecore/content/OneWeb/OneWeb/OneWeb/Presentation/Rendering Variants/OneWeb Product Card/Multi Column/default
DB: master
SharedFields:
- ID: "9e02be90-89ab-4127-9e33-2a2fb3ac5a77"
  Hint: Template
  Value: |
    {{-if i_item
    	case i_item.template_name
    		when "Product Detail"
    			sc_execute i_datasource "Product Detail Scriban"
    		else 
    			sc_execute  i_datasource "Card Scriban"
    	end
    end-}}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211224T182051Z
