---
ID: "ff9b026a-19e2-486c-97ed-13105e5cf173"
Parent: "83a8a63c-aadf-4f97-abe4-555a1f8ca28c"
Template: "83a8a63c-aadf-4f97-abe4-555a1f8ca28c"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Search/Rendering Parameters/OneWeb Search Template Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211211T190026Z
