---
ID: "9690e6fa-2652-4fbc-a83c-7520e8d2b4c2"
Parent: "7aca1415-12d8-40d9-aa3e-b59537a809ca"
Template: "7aca1415-12d8-40d9-aa3e-b59537a809ca"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Testimonial Card Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {3139FAD4-8E19-4AD1-90F6-C3E870F87DD8}
    {7ACA1415-12D8-40D9-AA3E-B59537A809CA}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
