---
ID: "5d784aa5-4ea5-47b4-9fa9-66989bdbb496"
Parent: "34d6e236-d095-48ed-82e1-49b3931bcaa3"
Template: "34d6e236-d095-48ed-82e1-49b3931bcaa3"
Path: /sitecore/templates/Project/OneWeb/OneWeb/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211114T073817Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
