---
ID: "657d540d-e855-44ce-a71b-c1fb4168a8ca"
Parent: "86ed7be4-4374-4b75-9aff-8d2c33616e82"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Product List/Content/Product List
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: /sitecore/content/OneWeb/OneWeb/OneWeb/Home
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Multiroot Treelist
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: Count of total number of selected items should be even to display all.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211129T112658Z
