---
ID: "697d54e4-71c8-4be9-af59-aae7585e7a1b"
Parent: "c0bcbc8e-3a45-4829-a3d9-2fc4653d2cfb"
Template: "c0bcbc8e-3a45-4829-a3d9-2fc4653d2cfb"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Rendering Parameters/OneWeb Popup Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211201T081731Z
