---
ID: "366fdb80-010a-42b8-9726-63acf77c44d0"
Parent: "567cbeb7-95ce-4e2b-b321-005f4b56ae37"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/OneWeb/OneWeb/OneWeb/OneWebV2/gulp/tasks/watchSassSource
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/F0BD550AD6784511988330B9B16A9312.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "f1f24774-d917-4b5a-8b59-0567078086bf"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KLy8NCmltcG9ydCBsb2dpbiBmcm9tICcuL2xvZ2luJzsNCmltcG9ydCBjb25maWcgZnJvbSAnLi4vY29uZmlnJzsNCmltcG9ydCB7IGZpbGVBY3Rpb25SZXNvbHZlciB9IGZyb20gJy4uL3V0aWwvZmlsZUFjdGlvblJlc29sdmVyJzsNCg0KZ3VscC50YXNrKCd3YXRjaC1zb3VyY2Utc2FzcycsIFsnbG9naW4nXSwgKCkgPT4gew0KICAgIHZhciBjb25mID0gY29uZmlnLnNhc3M7DQogICAgcmV0dXJuIHdhdGNoKGNvbmYucm9vdCwgZnVuY3Rpb24gKGZpbGUpIHsNCiAgICAgICAgaWYgKCFjb25mLmRpc2FibGVTb3VyY2VVcGxvYWRpbmcpIHsNCiAgICAgICAgICAgIGZpbGVBY3Rpb25SZXNvbHZlcihmaWxlKTsNCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgIGNvbnNvbGUubG9nKCdVcGxvYWRpbmcgcHJldmVudGVkIGJlY2F1c2UgdmFsdWUgZGlzYWJsZVNvdXJjZVVwbG9hZGluZzp0cnVlJy55ZWxsb3cpOw0KDQogICAgICAgIH0NCiAgICB9KQ0KfSk7DQoNCmd1bHAudGFzaygnc2Fzcy1zb3VyY2Utd2F0Y2gnLCBbJ2xvZ2luJ10sDQogICAgZnVuY3Rpb24gKCkgew0KICAgICAgICBnbG9iYWwuaXNXYXRjaGluZyA9IHRydWU7DQogICAgICAgIGd1bHAucnVuKCd3YXRjaC1zb3VyY2Utc2FzcycpDQogICAgfSk=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 722
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T065214Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
