---
ID: "8396f013-cca8-4dfa-a5bb-8ccdfc0b4f44"
Parent: "6e575d03-40c3-49e5-8e59-f993ded78609"
Template: "6e575d03-40c3-49e5-8e59-f993ded78609"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Login/Rendering Parameters/OneWeb Users Table Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220323T131144Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
