---
ID: "c1fb5481-5cbb-4d46-ade8-28ae1a87408b"
Parent: "bf76472c-d9f7-4a4b-83fd-03bf7ba51a55"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Business/OneWeb Business/Business Information/Products
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:$site/*[@@name='Data']/*[@@templatename='OneWeb Business Wrapper Folder']/*[@@templatename='OneWeb Business Product Folder']"
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: TreelistEx
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211222T040138Z
