---
ID: "d591c56f-6591-4ca9-ba10-d3b97e5aeca4"
Parent: "46dddc28-552f-4906-a7af-bcdb525a51f4"
Template: "46dddc28-552f-4906-a7af-bcdb525a51f4"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Comparison Cards Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {B8B8EAA3-D3B3-4CB0-A337-8132EF69005F}
    {46DDDC28-552F-4906-A7AF-BCDB525A51F4}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
