---
ID: "dfdf2144-aa1c-4026-ba4a-e158bbc5f79d"
Parent: "96b7a1d9-6fc0-4ff5-8fa3-20f5b5ec5298"
Template: "96b7a1d9-6fc0-4ff5-8fa3-20f5b5ec5298"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Support Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {8A157750-D8F9-433A-94FE-C875B5580D80}
    {96B7A1D9-6FC0-4FF5-8FA3-20F5B5EC5298}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
