---
ID: "da4eec67-fc70-44b0-b819-8038c71529d0"
Parent: "40ba3e3e-3603-4f69-a8f3-5085c8884763"
Template: "55d811b7-081e-42fd-bdd8-803e8ad31840"
Path: /sitecore/content/OneWeb/OneWeb/OneWeb/Settings/OneWeb Search Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211201T112317Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
