---
ID: "51dc8fab-b100-497a-854c-8b087657dd83"
Parent: "2dab00c3-0548-4391-9113-5f8c2605231e"
Template: "2dab00c3-0548-4391-9113-5f8c2605231e"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Content Card/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220628T195125Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
