---
ID: "40328b9a-cded-44ea-8e5c-d010d7968cea"
Parent: "3da0dad9-8710-4ea5-88e4-0be994fa6f11"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/OneWeb/OneWeb/OneWeb/Presentation/Rendering Variants/OneWeb User Search Box/Default
DB: master
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{52116EEE-72FA-41C1-8DB0-7EF6BE0D39EE}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220316T071753Z
