---
ID: "b56b5115-f57a-4a1d-a772-8740f4eaba21"
Parent: "4f251c3e-125d-4b02-863c-2e81ce6feca2"
Template: "4f251c3e-125d-4b02-863c-2e81ce6feca2"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Login/Datasource/OneWeb User API Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220324T100024Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
