---
ID: "cde54500-bb21-4f41-b6ff-9486e4d3186d"
Parent: "4c66a917-60dd-42c7-9b74-a84264cacbb2"
Template: "4c66a917-60dd-42c7-9b74-a84264cacbb2"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Navigation/Datasource/OneWeb Navigation Link/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220706T121741Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
