---
ID: "aca9c8d2-d457-4fcb-bff2-43ea46c22e98"
Parent: "3f2dc1dc-7587-4510-a5f2-f97d7b0ad768"
Template: "3f2dc1dc-7587-4510-a5f2-f97d7b0ad768"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Hero/Datasource/OneWeb Image List Banner/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211128T112405Z
