---
ID: "be016ebc-1f14-41af-b360-414259fcfd7f"
Parent: "98e8931b-4edd-43f3-973d-1c6e44d41ccd"
Template: "98e8931b-4edd-43f3-973d-1c6e44d41ccd"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Header Strip Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {552C7C41-FCF3-45A9-A813-3D75A4D5C654}
    {6A17FD68-E31C-422E-9485-24492D5EBC5F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
