---
ID: "88440ca0-e31b-40c9-ad8f-560f9b32a853"
Parent: "e0ed3b59-4400-4464-8b05-80d9d39ba6b7"
Template: "97167eaa-fbde-43ac-aace-f453d151cd87"
Path: /sitecore/content/OneWeb/OneWeb/OneWeb/Home/Products
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220330T161333Z
    - ID: "2858f997-e26f-4084-ab19-bcd957034d63"
      Hint: Title
      Value: Products
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
