---
ID: "49145905-594b-4ee6-8d72-79adbdc98800"
Parent: "e0ed3b59-4400-4464-8b05-80d9d39ba6b7"
Template: "97167eaa-fbde-43ac-aace-f453d151cd87"
Path: /sitecore/content/OneWeb/OneWeb/OneWeb/Home/ProductList
DB: master
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Type: Checklist
  Value: |
    {61BD64D6-809E-40AE-9297-2724A19329B3}
    {D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{367D2B7A-CDCE-49F1-9EB4-F7388E9B0EDB}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{B3F6B8C8-CF9F-4D4D-A357-A14997BB2F87}"
          p:before="*"
          s:ds="{419F0C96-D9A8-4995-8A1A-8CB403840B82}"
          s:id="{22FDD975-E198-42BC-BC36-F9B8319133DD}"
          s:par="GridParameters&amp;Related Product List&amp;Autoplay&amp;Autoplay Speed&amp;Show Arrows=1&amp;Show Dots&amp;Slides To Show=3&amp;Slides To Show Mobile=1.2&amp;Slides To Show Tab=2.2&amp;Custom Slider Class&amp;Carousel Desktop Disable&amp;FieldNames=%7B1B00F5AC-4D75-4A30-B7D4-4685B59FBCB9%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=5"
          s:ph="/main/ow-container-fluid-1/ow-row-2/ow-container-3" />
        <r
          uid="{1F447B67-CA8F-423E-8F49-2163BB7F1035}"
          p:after="r[@uid='{B3F6B8C8-CF9F-4D4D-A357-A14997BB2F87}']"
          s:ds=""
          s:id="{A6E7A90A-4B1A-4936-A512-2A918A04B3A6}"
          s:par="GridParameters&amp;BackgroundColor&amp;Styles&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
          s:ph="/main/ow-container-fluid-1/ow-row-2" />
        <r
          uid="{03B96E44-4091-414A-A7B0-2CFA8DD1EC4E}"
          p:after="r[@uid='{1F447B67-CA8F-423E-8F49-2163BB7F1035}']"
          s:id="{BFE4C09B-0469-4348-A5ED-08ED00E18853}"
          s:par="BackgroundColor&amp;Styles&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
          s:ph="/main/ow-container-fluid-1" />
        <r
          uid="{CF3B9F7F-C5FA-4503-812B-A7B05A5674C3}"
          p:after="*[1=2]"
          s:ds=""
          s:id="{4F1D055A-D52F-4581-944C-FE1E641BDA34}"
          s:par="GridParameters&amp;BackgroundColor&amp;Styles=%7BDC3E505E-99C7-427B-8A25-29D9A6838161%7D&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1&amp;OwClass=text-center"
          s:ph="main" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211127T191132Z
    - ID: "2858f997-e26f-4084-ab19-bcd957034d63"
      Hint: Title
      Value: |
        Businesses
        
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Businesses
