---
ID: "e57a1d07-6e84-4389-b85b-a0cd0bf2af25"
Parent: "d8ec76ea-b28f-4e27-b420-e97c19c521ee"
Template: "d8ec76ea-b28f-4e27-b420-e97c19c521ee"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Structure/OneWeb Section Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {377BCA24-5F58-4013-A109-3B0C5260FFCD}
    {D8EC76EA-B28F-4E27-B420-E97C19C521EE}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
