---
ID: "1f5be9d5-9f10-4d38-bc60-a112dbd3e66d"
Parent: "ef431934-5da7-4662-bbd5-4391ced35b39"
Template: "ef431934-5da7-4662-bbd5-4391ced35b39"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Rendering Parameters/OneWeb Locations Rendering Parameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
