---
ID: "4cf149a6-be97-40f8-b229-781fd792f02d"
Parent: "c70d08b3-d635-4a84-b28b-6016711253de"
Template: "c70d08b3-d635-4a84-b28b-6016711253de"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Page Content/Datasource/OneWeb Resource Listing/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211129T112128Z
