---
ID: "e678d5ab-609e-4fd1-81a8-8e08b12ed193"
Parent: "45b4e38d-7be2-43bb-a133-220ad50c2a15"
Template: "45b4e38d-7be2-43bb-a133-220ad50c2a15"
Path: /sitecore/templates/Foundation/OneWeb/Base/_BaseMobile Image/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220211T172224Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
