---
ID: "1a3b8d75-b0f3-4043-8e92-5900d28925a2"
Parent: "0e8fb3e8-d2ac-4a35-960c-6943be6f77ec"
Template: "0e8fb3e8-d2ac-4a35-960c-6943be6f77ec"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Navigation/Rendering Parameters/OneWeb Navigation Link List Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220706T125341Z
