---
ID: "463bd1a3-a0d4-443d-9f25-3ee60111bea3"
Parent: "11ffc237-4edb-4787-ad4e-87bc23bf2307"
Template: "11ffc237-4edb-4787-ad4e-87bc23bf2307"
Path: /sitecore/templates/Feature/OneWeb/OneWeb Media/Rendering Parameters/OneWeb Media Download Card Rendering Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220124T072157Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
