---
ID: "0cf186e2-5771-4fc7-a4e9-7bf287417995"
Parent: "662a3080-336d-4d89-a201-b755c99c9687"
Template: "97167eaa-fbde-43ac-aace-f453d151cd87"
Path: "/sitecore/content/OneWeb/OneWeb/OneWeb/Home/Contact-Us/Product Support"
DB: master
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{367D2B7A-CDCE-49F1-9EB4-F7388E9B0EDB}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{2A918814-9A5B-46A5-A3DA-209B36A15D2F}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{0CEDAEB6-FA8C-47D0-A322-34E0521A526B}"
          p:before="*"
          s:ds="{53306818-9DC2-43A4-9035-193139C4D153}"
          s:id="{8FCBC59C-90EB-45A3-9DD2-8E1300BA189A}"
          s:par="GridParameters&amp;Configuration=%7B17F348A3-C238-48AF-8C3D-6A6E23A3083E%7D&amp;FieldNames=%7B10FAAD8E-EDBD-4A26-A6BB-AC4790EBA7AB%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier"
          s:ph="/main/ow-container-1/ow-row-2/ow-column-3/ow-search-filter-wrapper" />
        <r
          uid="{C3526727-9C19-4395-BECB-7B4B88BB15AE}"
          p:after="r[@uid='{0CEDAEB6-FA8C-47D0-A322-34E0521A526B}']"
          s:id="{E97323A4-2C43-45D6-811E-8B4DDE6F4EFA}"
          s:par=""
          s:ph="/main/ow-container-1/ow-row-2/ow-column-3" />
        <r
          uid="{8A622205-CF9B-4C21-B383-76F831AF0722}"
          p:after="r[@uid='{C3526727-9C19-4395-BECB-7B4B88BB15AE}']"
          s:ds="{6348645D-419A-481E-ABAF-786256CB75FB}"
          s:id="{A518A432-35D8-4945-B8A6-52874CBA07A7}"
          s:par="GridParameters&amp;FieldNames=%7B31889B83-EC38-418C-88BE-30FD7E3197E0%7D&amp;Styles&amp;Reset Caching Options&amp;SearchTextBoxVisible=1&amp;RenderingIdentifier"
          s:ph="/main/ow-container-1/ow-row-2/ow-column-5" />
        <r
          uid="{6CBF9282-DC54-49BD-AB1A-550FB9712619}"
          p:after="r[@uid='{8A622205-CF9B-4C21-B383-76F831AF0722}']"
          s:ds="{17F348A3-C238-48AF-8C3D-6A6E23A3083E}"
          s:id="{8FCBC59C-90EB-45A3-9DD2-8E1300BA189A}"
          s:par="GridParameters&amp;Configuration=%7B17F348A3-C238-48AF-8C3D-6A6E23A3083E%7D&amp;FieldNames=%7B2203DD70-47A6-4265-991E-D8A5271F38F4%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier"
          s:ph="/main/ow-container-1/ow-row-2/ow-column-5" />
        <r
          uid="{2CE2F1A8-3DC7-4F75-9541-798B7B561901}"
          p:after="r[@uid='{6CBF9282-DC54-49BD-AB1A-550FB9712619}']"
          s:ds=""
          s:id="{B90B9CDC-71B1-4146-85E4-02AAC366F246}"
          s:par="GridParameters=%7B287E897B-28E7-4D93-BA36-C780DDFCE01C%7D&amp;BackgroundColor&amp;Styles&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
          s:ph="/main/ow-container-1/ow-row-2" />
        <r
          uid="{41D45F3B-5D64-4397-840B-3B9778AE7E1A}"
          p:after="r[@uid='{2CE2F1A8-3DC7-4F75-9541-798B7B561901}']"
          s:ds=""
          s:id="{B90B9CDC-71B1-4146-85E4-02AAC366F246}"
          s:par="GridParameters=%7B7F0C5511-0738-4742-A6B8-343E2438F908%7D&amp;BackgroundColor&amp;Styles&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=5"
          s:ph="/main/ow-container-1/ow-row-2" />
        <r
          uid="{9DD5DBF2-A116-4B07-9098-10D557E03924}"
          p:after="r[@uid='{41D45F3B-5D64-4397-840B-3B9778AE7E1A}']"
          s:id="{BFE4C09B-0469-4348-A5ED-08ED00E18853}"
          s:par="BackgroundColor&amp;Styles&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
          s:ph="/main/ow-container-1" />
        <r
          uid="{737979E6-7BDE-4A9D-8C8F-A8F87EF3A63B}"
          p:after="*[1=2]"
          s:id="{A6E7A90A-4B1A-4936-A512-2A918A04B3A6}"
          s:par="GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;BackgroundColor&amp;Styles&amp;BackgroundImage&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
          s:ph="main" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211209T220846Z
    - ID: "2858f997-e26f-4084-ab19-bcd957034d63"
      Hint: Title
      Value: Product Support
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{5644FD40-205B-4192-B01D-542C525064C5}"
    - ID: "4c2f221f-9426-45ed-9eeb-c79bb3169565"
      Hint: StickyNotes
      Value: |
        {"items":[]}
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Support
