---
ID: "3e3648c6-9ff7-4cc5-9729-b40934204800"
Parent: "e7d6d9d3-4170-4430-93cc-7675cc4a378c"
Template: "e7d6d9d3-4170-4430-93cc-7675cc4a378c"
Path: /sitecore/templates/Foundation/OneWeb/Base/_BaseBriefDescription/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211230T103230Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
