---
ID: "53ad6779-87a2-4658-be2d-f1a4dafc09fd"
Parent: "4c96dce5-a442-488b-ad49-cc2659c246bd"
Template: "4c96dce5-a442-488b-ad49-cc2659c246bd"
Path: /sitecore/templates/Foundation/OneWeb/Base/DateFolder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{A87A00B1-E6DB-45AB-8B54-636FEC3B5523}"
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20070126T130200
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
